// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommunicationClient is the client API for Communication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunicationClient interface {
	StreamFrequencies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Communication_StreamFrequenciesClient, error)
}

type communicationClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicationClient(cc grpc.ClientConnInterface) CommunicationClient {
	return &communicationClient{cc}
}

func (c *communicationClient) StreamFrequencies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Communication_StreamFrequenciesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Communication_ServiceDesc.Streams[0], "/api.Communication/streamFrequencies", opts...)
	if err != nil {
		return nil, err
	}
	x := &communicationStreamFrequenciesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Communication_StreamFrequenciesClient interface {
	Recv() (*Frequency, error)
	grpc.ClientStream
}

type communicationStreamFrequenciesClient struct {
	grpc.ClientStream
}

func (x *communicationStreamFrequenciesClient) Recv() (*Frequency, error) {
	m := new(Frequency)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommunicationServer is the server API for Communication service.
// All implementations must embed UnimplementedCommunicationServer
// for forward compatibility
type CommunicationServer interface {
	StreamFrequencies(*Empty, Communication_StreamFrequenciesServer) error
	mustEmbedUnimplementedCommunicationServer()
}

// UnimplementedCommunicationServer must be embedded to have forward compatible implementations.
type UnimplementedCommunicationServer struct {
}

func (UnimplementedCommunicationServer) StreamFrequencies(*Empty, Communication_StreamFrequenciesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamFrequencies not implemented")
}
func (UnimplementedCommunicationServer) mustEmbedUnimplementedCommunicationServer() {}

// UnsafeCommunicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunicationServer will
// result in compilation errors.
type UnsafeCommunicationServer interface {
	mustEmbedUnimplementedCommunicationServer()
}

func RegisterCommunicationServer(s grpc.ServiceRegistrar, srv CommunicationServer) {
	s.RegisterService(&Communication_ServiceDesc, srv)
}

func _Communication_StreamFrequencies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommunicationServer).StreamFrequencies(m, &communicationStreamFrequenciesServer{stream})
}

type Communication_StreamFrequenciesServer interface {
	Send(*Frequency) error
	grpc.ServerStream
}

type communicationStreamFrequenciesServer struct {
	grpc.ServerStream
}

func (x *communicationStreamFrequenciesServer) Send(m *Frequency) error {
	return x.ServerStream.SendMsg(m)
}

// Communication_ServiceDesc is the grpc.ServiceDesc for Communication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Communication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Communication",
	HandlerType: (*CommunicationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamFrequencies",
			Handler:       _Communication_StreamFrequencies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/api.proto",
}
